NAME = Fixed_2

FLAGS = -Wall -Werror -Wextra -std=c++98

SRCS =	main.cpp \
		Fixed.cpp \

all : $(NAME)

$(NAME) : $(SRCS)
		c++ $(FLAGS) $(SRCS) -o Fixed_2

clean :
		rm -rf $(NAME)

fclean :
		rm -rf $(NAME)

re : fclean all
