NAME = Sed
HHH
FLAGS = -Wall -Werror -Wextra -std=c++98
HHH
SRCS =	main.cpp \
HHH
all : $(NAME)
HHH
$(NAME) : $(SRCS)
HHH	HHH	c++ $(FLAGS) $(SRCS) -o Sed
HHH
clean :
HHH	HHH	rm -rf $(NAME)
HHH
fclean :
HHH	HHH	rm -rf $(NAME)
HHH
re : fclean all
HHH
