NAME = Sed

FLAGS = -Wall -Werror -Wextra -std=c++98

SRCS =	main.cpp \

all : $(NAME)

$(NAME) : $(SRCS)
		c++ $(FLAGS) $(SRCS) -o Sed

clean :
		rm -rf $(NAME)

fclean :
		rm -rf $(NAME)

re : fclean all